(defun select-current-line ()
  (interactive)
  (end-of-line)
  (set-mark (line-beginning-position))
  (kill-region (region-beginning) (region-end))
  (yank)
  (other-window 1)
  (yank)
  (term-send-input)
  (other-window 1)
  ;; (next-line 1)
  (beginning-of-line)
  )

(defun copy-term-output ()
  (interactive)
  (end-of-line)
  (set-mark (line-beginning-position))
  (kill-region (region-beginning) (region-end))
  (yank)
  (other-window 1)
  ;; (previous-line)
  (set-mark (line-beginning-position))
  (search-backward (substring-no-properties (car kill-ring)))
  (end-of-line)
  (kill-region (region-beginning) (region-end))
  (yank)
  (end-of-buffer)
  (other-window 1)
  (newline)
  (yank)
  (newline)
  (beginning-of-line)
  )

(global-set-key (kbd "C-c l") 'select-current-line)
(global-set-key (kbd "C-c r") 'copy-term-output)
